.TH FBPDF 1 "JUNE 2022"
.SH NAME
fbpdf \- framebuffer PDF viewer
.SH SYNOPSIS
.B fbpdf
.RB [ -r
.IR rotation ]
.RB [ -z
.IR zoom_x10 ]
.RB [ -p
.IR page_number ]
.IR filename
.SH DESCRIPTION
.P
.B fbpdf
is a small framebuffer PDF viewer which uses the MuPDF backend.
.P
.B fbpdf2
is similar to fbpdf, but uses poppler as backend.
.P
.B fbdjvu
is a djvu viewer.
.P
The options documented here are available in all three programs.
.SH OPTIONS
.TP
.BI "\-r " rotation
Rotate specified number of degrees
.TP
.BI "\-z " zoom_x10
Zoom by a multiple of ten
.TP
.BI "\-p " page_number
Go to specified page
.SH KEY BINDINGS
Most of the key bindings accept a numerical prefix.
For instance, '^F' tells fbpdf to show the next page
while '5^F' tells it to show the fifth next page.

.TP
.B h
Scroll left
.TP
.B j
Scroll down
.TP
.B k
Scroll up
.TP
.B l
Scroll right
.TP
.B ^d | <Space>
Page down
.TP
.B ^u | <Backspace>
Page up
.TP
.B ^f | J
Go to next page
.TP
.B ^b | K
Go to previous page
.TP
.B H
Show page top
.TP
.B M
Center the page vertically
.TP
.B L
Show page bottom
.TP
.B C
Center the page horizontally
.TP
.B f
Fit page height
.TP
.B w
Fit page width
.TP
.B W
Fit page contents horizontally
.TP
.B [
Align with the left edge of the page
.TP
.B ]
Align with the right edge of the page
.TP
.B {
Align with the leftmost character on the page
.TP
.B }
Align with the rightmost character on the page
.TP
.B <prefix>G
Go to specified page, default to the last page if no prefix
.TP
.B <prefix>o
Set page number (for 'G' command only)
.TP
.B <prefix>O
Set page number and go to current page
.TP
.B <prefix>r
Rotate specified number of degrees
.TP
.B <prefix>z
Zoom by a multiple of ten in percentage (i.e. '15z' = 150%)
.TP
.B <prefix>Z
Set the default zoom level for 'z' command
.TP
.B m<mark>
Mark page as <mark>, could be any letter
.TP
.B '<mark>
Jump to the page marked as <mark>
.TP
.B `<mark>
Jump to the page and position marked as <mark>
.TP
.B ^[ / <Esc>
Clear numerical prefix
.TP
.B <prefix>d
Sleep specified seconds before the next command
.TP
.B I
Invert colors
.TP
.B i
Display file information
.TP
.B e
Reload file
.TP
.B ^l
Redraw screen
.TP
.B q
Quit program
.SH AUTHOR
Ali Gholami Rudi <aligrudi at gmail dot com>
